lang = {
    'NOT_IN_CHANNEL': ":no_entry: Necesitas estar en el mismo canal que yo para hacer eso",
    'NOT_CONNECTED': ":no_entry: Necesitas estar conectado a un canal de voz",
    'QUEUE_MAX_REACHED': ":no_entry: Solo pueden haber un máximo de 10 canciones en cola",
    'QUEUE_IS_EMPTY': ":timer: La cola de canciones se encuentra vacía",
    'QUEUE_LIST_MESSAGE': ":timer: **Lista de canciones en espera:**\n{}",
    'QUEUE_SONG_ADDED': ":watch: La canción **'{}'** fue añadida a la cola",
    'ACTUAL_VOLUME': ":loud_sound: Mi volumen actual es de **{}%**",
    'VOLUME_CHANGED': ":loud_sound: El volumen ha sido cambiado a **{}%**",
    'LOADING_SONG': ':hourglass_flowing_sand: *Cargando {}...*',
    'PLAYING_SONG': ':musical_note: **Reproduciendo:** {} - **Añadida por**: {}',
    'SEEK_BAD_FORMAT': ":no_entry: El tiempo debe tener formato 00:00",
    'DISCONNECT_WHILE_PLAYING': ":no_entry: No me puedo desconectar mientras reproduzco música",
    'NOT_FOUND': ":frowning2: Lo siento, no pude encontrar esa canción",
    'SONG_NEEDED': ":no_entry: Necesitas especificar una canción",
    'QUEUE_SONG_FAILED': ":frowning2: No he podido añadir esa canción a la lista de espera, inténtalo nuevamente",
}